/*
 * File: app/controller/DashboardController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.controller.DashboardController', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        var dashBoard = this;

        var dashBoardContextMenu = new Ext.menu.Menu({
            items:
            [
                { text: 'NIC 관리',
                 handler: function() {
                     alert('NIC 관리');
                 }
                },
                { text: '라우팅',
                 handler: function() {
                     alert('라우팅');
                 }
                },
                { text: '파이어월',
                 handler: function() {
                     alert('파이어월');
                 }
                },
                { text: 'NAT 관리',
                 handler: function() {
                     alert('NAT 관리');
                 }
                },
                {
                    xtype: 'menuseparator'
                },
                { text: 'VM 시작/중단',
                 handler: function() {
                     alert('VM 시작/중단');
                 }
                }
            ]

        });

        //Dashboard Menu Constants
        Ext.define('dashboardConstants', {
            singleton: true,
            me : dashBoard,
            contextMenu: dashBoardContextMenu
        });
    }

});
