/*
 * File: app/controller/GlobalController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.controller.GlobalController', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        var intervalId1, intervalId2, intervalId3;
        var chartDataStore = Ext.getStore('chartDataStore');
        var cpuChart = Ext.getCmp('cpuChart');
        var memoryChart = Ext.getCmp('memoryChart');
        var networkChart = Ext.getCmp('networkChart');

        // Global variables를 정의하는 구문으로 GlobalData.urlPrefix, GlobalData.serverSize 등으로 어디에서든 접근이 가능하다.
        Ext.define('GlobalData', {
            singleton: true,

            intervalId1: intervalId1,
            intervalId2: intervalId2,
            intervalId3: intervalId3,
            chartDataStore: chartDataStore,
            cpuChart: cpuChart,
            memoryChart: memoryChart,
            networkChart: networkChart
        });
    }

});
