/*
 * File: app/controller/UserController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.controller.UserController', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        var user = this;

        //VM Host Tree Constants
        Ext.define('userConstants', {
            singleton: true,
            me : user

        });
    },

    popAddUserWindow: function() {
        //User 등록 팝업 호출
        var popWindow = Ext.create("widget.AddUserWindow");
        popWindow.show();
    },

    createUser: function(button) {

    }

});
