/*
 * File: app/view/AddVmWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.AddVmWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.AddVmWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 280,
    width: 430,
    resizable: false,
    title: 'VM 추가',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'addVmForm',
                    itemId: 'addVmForm',
                    bodyPadding: 15,
                    header: false,
                    title: 'My Form',
                    fieldDefaults: {
                        msgTarget: 'side',
                        labelWidth: 120
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'VM Host',
                            name: 'vmhostName'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '이름',
                            name: 'name',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            validator: function(value) {
                                if(value == "없음(생성불가)") {
                                    return 'This field is required';
                                } else {
                                    return true;
                                }
                            },
                            anchor: '100%',
                            fieldLabel: 'Template',
                            name: 'tname',
                            allowBlank: false,
                            editable: false,
                            displayField: 'name',
                            store: 'ComboVmTemplateStore',
                            valueField: 'name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Host Name',
                            name: 'hostname',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'VM Type',
                            name: 'vmtype',
                            editable: false,
                            store: [
                                [
                                    'nfv',
                                    'NFV VM'
                                ],
                                [
                                    'vm',
                                    '일반 VM'
                                ]
                            ]
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Vendor',
                            name: 'vendor'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'vmhostId'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                vmHostConstants.me.createVM(button);
                            },
                            padding: '3 8 3 8',
                            text: '생성'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                GLOBAL.me.closeWindow(button);
                            },
                            padding: '3 8 3 8',
                            text: '취소'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});