/*
 * File: app/view/AthenaSpider.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.AthenaSpider', {
    extend: 'Ext.container.Viewport',

    requires: [
        'spider.view.DashboardPanel',
        'spider.view.vmMgmtPanel',
        'spider.view.MyContainer1',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Label',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.panel.Tool',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.layout.container.*',
        'Ext.ux.GMapPanel',
        'Ext.util.Point',
        'Ext.data.JsonStore',
        'Ext.chart.*',
        'Ext.grid.plugin.RowEditing'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    margins: '0 0 5 0',
                    region: 'north',
                    height: 60,
                    id: 'northPanel',
                    itemId: 'northPanel',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            margins: '3 3 3 3',
                            border: false,
                            id: 'logoImgPanel',
                            itemId: 'logoImgPanel',
                            width: 197,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 54,
                                    id: 'logoImg',
                                    itemId: 'logoImg',
                                    width: 147,
                                    src: 'resources/images/logo/osc-logo.png'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            id: 'headerPanel',
                            itemId: 'headerPanel',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    height: 30,
                                    layout: {
                                        type: 'hbox',
                                        align: 'bottom'
                                    },
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<a href="#"><b>Administrator</b></a>',
                                            text: 'Administrator'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<a href="javascript:">Logout</a>',
                                            id: 'logoutLabel',
                                            itemId: 'logoutLabel'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'panel',
                                    margins: '0 0 0 5',
                                    id: 'mainBtnPanel',
                                    itemId: 'mainBtnPanel',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'dashboardBtn',
                                            itemId: 'dashboardBtn',
                                            enableToggle: true,
                                            icon: 'resources/images/icons/monitor.png',
                                            pressed: true,
                                            scale: 'medium',
                                            text: 'Dashboard'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'managementBtn',
                                            itemId: 'managementBtn',
                                            enableToggle: true,
                                            icon: 'resources/images/icons/management.png',
                                            scale: 'medium',
                                            text: 'VM Management'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'monitoringBtn',
                                            itemId: 'monitoringBtn',
                                            enableToggle: true,
                                            icon: 'resources/images/icons/chart_line.png',
                                            scale: 'medium',
                                            text: 'Monitoring'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'mainViewBtn',
                                            itemId: 'mainViewBtn',
                                            enableToggle: true,
                                            icon: 'resources/images/icons/server_link.png',
                                            scale: 'medium',
                                            text: 'Main View'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    id: 'westPanel',
                    itemId: 'westPanel',
                    width: 200,
                    collapsible: true,
                    title: 'Server List',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    tools: [
                        {
                            xtype: 'tool',
                            type: 'refresh'
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            margins: '5 5 5 5',
                            height: 25,
                            id: 'locationPanel',
                            itemId: 'locationPanel',
                            dockedItems: [
                                {
                                    xtype: 'combobox',
                                    dock: 'top',
                                    fieldLabel: 'Locations',
                                    labelWidth: 60,
                                    value: 'NCIA Daejeon',
                                    store: [
                                        'NCIA Daejeon',
                                        'NCIA Kwangju'
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            id: 'menuPanel',
                            itemId: 'menuPanel',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'panel',
                                    region: 'center',
                                    id: 'serverListPanel',
                                    itemId: 'serverListPanel',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            margins: '8 5 0 8',
                                            height: 30,
                                            id: 'btnPanel',
                                            itemId: 'btnPanel',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    id: 'btnPanel1',
                                                    itemId: 'btnPanel1',
                                                    width: 23,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            id: 'expandImg',
                                                            itemId: 'expandImg',
                                                            margin: '5 0 0 0',
                                                            src: 'resources/images/icons/expand-all.png'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    id: 'btnPanel2',
                                                    itemId: 'btnPanel2',
                                                    width: 15,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            margin: '5 0 0 0',
                                                            src: 'resources/images/icons/separator.png'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    id: 'btnPanel3',
                                                    itemId: 'btnPanel3',
                                                    width: 25,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            id: 'collapseImg',
                                                            itemId: 'collapseImg',
                                                            margin: '5 0 0 0',
                                                            src: 'resources/images/icons/collapse-all.png'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 0.3
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    header: false,
                                                    title: 'My Panel',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, e) {
                                                                treeConstants.me.popAddVMHostWindow();
                                                            },
                                                            text: 'VM  Host 추가'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            id: 'listWrapPanel',
                                            itemId: 'listWrapPanel',
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'treepanel',
                                                    id: 'listMenuPanel',
                                                    itemId: 'listMenuPanel',
                                                    style: '{height: 100%; overflow: scroll;}',
                                                    autoScroll: true,
                                                    rootVisible: false,
                                                    viewConfig: {
                                                        autoScroll: true,
                                                        preserveScrollOnRefresh: true
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'center',
                    id: 'centerContainer',
                    itemId: 'centerContainer',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'toolbar',
                            region: 'north',
                            height: 45,
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 27,
                                    margin: '5 10 0 10',
                                    width: 120,
                                    iconAlign: 'right',
                                    text: 'NCIA Daejeon'
                                },
                                {
                                    xtype: 'button',
                                    height: 27,
                                    margin: '5 0 0 10',
                                    width: 120,
                                    text: 'NCIA Kwangju'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            region: 'center',
                            id: 'centerPanel',
                            itemId: 'centerPanel',
                            layout: 'card',
                            header: false,
                            title: 'centerPanel',
                            items: [
                                {
                                    xtype: 'dashboardpanel',
                                    width: 150
                                },
                                {
                                    xtype: 'vmMgmtPanel'
                                },
                                {
                                    xtype: 'mycontainer1',
                                    height: 150,
                                    id: 'samplePanel'
                                },
                                {
                                    xtype: 'panel',
                                    header: false,
                                    title: 'My Panel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});