/*
 * File: app/view/DashboardPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.DashboardPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashboardpanel',

    requires: [
        'spider.view.DashBoardNodePanel',
        'Ext.panel.Panel'
    ],

    id: 'DashboardPanel',
    itemId: 'DashboardPanel',
    autoScroll: true,
    layout: 'column',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    columnWidth: 0.5,
                    id: 'DashBoardLeftPanel',
                    itemId: 'DashBoardLeftPanel',
                    layout: 'anchor'
                },
                {
                    xtype: 'panel',
                    columnWidth: 0.5,
                    id: 'DashBoardRightPanel',
                    itemId: 'DashBoardRightPanel',
                    layout: 'anchor'
                },
                {
                    xtype: 'DashBoardNodePanel',
                    hidden: true
                }
            ]
        });

        me.callParent(arguments);
    }

});