/*
 * File: app/view/DashBoardNodePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.DashBoardNodePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashboardnodepanel',

    requires: [
        'spider.view.MyPanel119',
        'Ext.form.FieldSet',
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    height: 214,
    header: false,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: 5,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 3,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 5,
                                            height: 30,
                                            text: 'VM Host #1',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'label',
                                            html: '<center><img src="resources/images/icons/status_01.png" width="36" height="36" border="0"></center>',
                                            style: '{text-align: center;}'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    cls: 'dashboard-graph-panel',
                                    height: 45,
                                    itemId: 'mypanel95',
                                    animCollapse: false,
                                    collapsed: false,
                                    collapsible: false,
                                    header: false,
                                    title: 'Graphite',
                                    titleCollapse: false,
                                    items: [
                                        {
                                            xtype: 'mypanel119'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    cls: 'dashboard-graph-panel',
                                    height: 45,
                                    itemId: 'mypanel98',
                                    animCollapse: false,
                                    collapsed: false,
                                    collapsible: false,
                                    header: false,
                                    title: 'Graphite',
                                    titleCollapse: false,
                                    items: [
                                        {
                                            xtype: 'mypanel119'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    cls: 'dashboard-graph-panel',
                                    height: 45,
                                    itemId: 'mypanel99',
                                    animCollapse: false,
                                    collapsed: false,
                                    collapsible: false,
                                    header: false,
                                    title: 'Graphite',
                                    titleCollapse: false,
                                    items: [
                                        {
                                            xtype: 'mypanel119'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            margin: '0 20 0 0',
                            width: 50,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_01.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_02.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_03.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                    text: 'NFV1-1'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                    text: 'NFV1-2'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                    text: 'NFV1-3'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                    text: 'NFV1-4'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><b>CPU</b></center>',
                                    style: '{display:inline-block;padding-top:10px;height: 36px;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_01.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_02.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_03.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><img src="resources/images/icons/status_04.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><b>Mem</b></center>',
                                    style: '{display:inline-block;padding-top:10px;height: 36px;}',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_05.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_04.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_03.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_02.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<center><b>Net</b></center>',
                                    style: '{display:inline-block;padding-top:10px;height: 36px;}',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_05.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_04.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_03.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: 36,
                                    html: '<center><img src="resources/images/icons/status_02.png" width="36" height="36" border="0"></center>',
                                    style: '{text-align: center;}'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var infoWindow = Ext.create("widget.VMInfoWindow");

        infoWindow.show();

    }

});