/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LoginWindow',

    requires: [
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 230,
    width: 420,
    resizable: false,
    closable: false,
    title: 'Athena Spider',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    height: 45,
                    html: '<h3>시스템을 사용하시려면 <font color="red">로그인</font>을 해주십시오.</h3>',
                    margin: '10 0 0 0',
                    style: 'text-align: center;'
                },
                {
                    xtype: 'form',
                    flex: 1,
                    id: 'loginForm',
                    itemId: 'loginForm',
                    margin: '5 0 0 0',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'userId',
                            fieldLabel: '사용자아이디',
                            labelAlign: 'right',
                            labelStyle: 'search',
                            labelWidth: 90,
                            name: 'userId',
                            allowBlank: false,
                            blankText: '사용자아이디는 필수 입력 항목입니다.'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'password',
                            fieldLabel: '비밀번호',
                            labelAlign: 'right',
                            labelWidth: 90,
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: '비밀번호는 필수 입력 항목입니다.'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    id: 'loginBtn',
                    margin: '5 0 15 150',
                    maxWidth: 100,
                    scale: 'medium',
                    text: '로그인'
                }
            ]
        });

        me.callParent(arguments);
    }

});