/*
 * File: app/view/MyContainer1.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.MyContainer1', {
    extend: 'Ext.container.Container',
    alias: 'widget.mycontainer1',

    requires: [
        'Ext.panel.Panel',
        'Ext.Img',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.Legend'
    ],

    itemId: 'mycontainer1',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'west',
                            split: true,
                            itemId: 'mypanel94',
                            width: 150,
                            animCollapse: false,
                            collapsed: false,
                            collapsible: false,
                            title: 'Graphite',
                            titleCollapse: false,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 200,
                                    id: 'graphiteImg',
                                    width: 200,
                                    src: 'http://192.168.0.3:8000/render/?width=200&height=200&_salt=1409028000.87&target=vyos.cpu.0.cpu.user.value&from=-2minutes'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            collapsed: false,
                            collapsible: false,
                            title: 'Sencha',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'chart',
                                    flex: 1,
                                    height: 250,
                                    id: 'sampleChart',
                                    itemId: 'sampleChart',
                                    animate: true,
                                    insetPadding: 20,
                                    store: 'SampleStore',
                                    axes: [
                                        {
                                            type: 'Category',
                                            fields: [
                                                'cate'
                                            ],
                                            grid: false,
                                            position: 'bottom'
                                        },
                                        {
                                            type: 'Numeric',
                                            fields: [
                                                'test'
                                            ],
                                            label: '',
                                            grid: true,
                                            position: 'left'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            label: '',
                                            xField: 'cate',
                                            yField: 'test',
                                            showMarkers: false,
                                            smooth: 3
                                        }
                                    ],
                                    legend: {

                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});