/*
 * File: app/view/VMHostInfoWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.view.VMHostInfoWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.VMHostInfoWindow',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.form.FieldSet',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    height: 500,
    id: 'VMHostInfoWindow',
    width: 750,
    overflowY: 'auto',
    title: 'VM Host Info',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'popVmHostInfoPanel',
                    itemId: 'popVmHostInfoPanel',
                    margin: '0 10 0 0',
                    header: false,
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'panel',
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 2,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            flex: 1,
                                            dock: 'top',
                                            margin: '5 5 2 5',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    html: '<center><img src="resources/images/icons/status_01.png" width="36" height="36" border="0"></center>',
                                                    itemId: 'VmHostStat',
                                                    minHeight: 36,
                                                    style: '{text-align: center;}',
                                                    width: 36
                                                },
                                                {
                                                    xtype: 'label',
                                                    html: '',
                                                    itemId: 'VmHostName',
                                                    margin: '0 10 0 0',
                                                    style: '{text-align: center;font-size : 18px;font-weight: bold;}',
                                                    text: 'VM Host1'
                                                }
                                            ]
                                        }
                                    ],
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            height: 45,
                                            collapsed: false,
                                            collapsible: false,
                                            header: false,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'chart',
                                                    flex: 1,
                                                    itemId: 'vmHostCpuChart',
                                                    margin: '0 30 0 10',
                                                    shadow: false,
                                                    insetPadding: 5,
                                                    store: 'VmHostCpuChartStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'date'
                                                            ],
                                                            label: {
                                                                renderer: function(v) {
                                                                    return "";
                                                                }
                                                            },
                                                            dashSize: 0,
                                                            grid: false,
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'user_cpu',
                                                                'system_cpu'
                                                            ],
                                                            label: '',
                                                            grid: false,
                                                            majorTickSteps: 1,
                                                            minorTickSteps: 1,
                                                            maximum: 100,
                                                            minimum: 0,
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            label: '',
                                                            xField: 'date',
                                                            yField: 'user_cpu',
                                                            showMarkers: false,
                                                            smooth: 3,
                                                            style: {
                                                                fill: '#3892d3',
                                                                'stroke-width': 1.2,
                                                                stroke: '#3892d3'
                                                            }
                                                        },
                                                        {
                                                            type: 'line',
                                                            label: '',
                                                            xField: 'date',
                                                            yField: 'system_cpu',
                                                            showMarkers: false,
                                                            smooth: 3,
                                                            style: {
                                                                fill: '#94AE0A',
                                                                'stroke-width': 1.2,
                                                                stroke: '#94AE0A'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            height: 45,
                                            collapsed: false,
                                            collapsible: false,
                                            header: false,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'chart',
                                                    flex: 1,
                                                    itemId: 'vmHostMemoryChart',
                                                    margin: '0 30 0 10',
                                                    shadow: false,
                                                    insetPadding: 5,
                                                    store: 'VmHostMemoryChartStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'date'
                                                            ],
                                                            label: {
                                                                renderer: function(v) {
                                                                    return "";
                                                                }
                                                            },
                                                            dashSize: 0,
                                                            grid: false,
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'memory'
                                                            ],
                                                            label: {
                                                                renderer: function(v) {
                                                                    
                                                                    if(v == null) {
                                                                        return v;
                                                                    }
                                                                    
                                                                    return (v/1024/1024).toFixed(0) + " Mb";
                                                                }
                                                            },
                                                            grid: false,
                                                            majorTickSteps: 1,
                                                            minorTickSteps: 1,
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            label: '',
                                                            xField: 'date',
                                                            yField: 'memory',
                                                            showMarkers: false,
                                                            smooth: 3,
                                                            style: {
                                                                fill: '#3892d3',
                                                                'stroke-width': 1.2,
                                                                stroke: '#3892d3'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            height: 45,
                                            collapsed: false,
                                            collapsible: false,
                                            header: false,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'chart',
                                                    flex: 1,
                                                    itemId: 'vmHostNetworkChart',
                                                    margin: '0 30 0 10',
                                                    shadow: false,
                                                    insetPadding: 5,
                                                    store: 'VmHostNetworkChartStore',
                                                    axes: [
                                                        {
                                                            type: 'Category',
                                                            fields: [
                                                                'date'
                                                            ],
                                                            label: {
                                                                renderer: function(v) {
                                                                    return "";
                                                                }
                                                            },
                                                            dashSize: 0,
                                                            grid: false,
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'Numeric',
                                                            fields: [
                                                                'col_0',
                                                                'col_1'
                                                            ],
                                                            label: '',
                                                            grid: false,
                                                            majorTickSteps: 1,
                                                            minorTickSteps: 1,
                                                            position: 'left'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            label: '',
                                                            xField: 'date',
                                                            yField: 'col_0',
                                                            showMarkers: false,
                                                            smooth: 3,
                                                            style: {
                                                                fill: '#3892d3',
                                                                'stroke-width': 1.2,
                                                                stroke: '#3892d3'
                                                            }
                                                        },
                                                        {
                                                            type: 'line',
                                                            label: '',
                                                            xField: 'date',
                                                            yField: 'col_1',
                                                            showMarkers: false,
                                                            smooth: 3,
                                                            style: {
                                                                fill: '#94AE0A',
                                                                'stroke-width': 1.2,
                                                                stroke: '#94AE0A'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1.5,
                                    margin: '10 20 0 0',
                                    padding: '3 0 3 3',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 180,
                                            overflowY: 'auto',
                                            layout: 'hbox',
                                            header: false,
                                            title: 'My Panel',
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    flex: 2,
                                                    itemId: 'vmNamePanel',
                                                    margin: 0,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            hidden: true,
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                                            text: ''
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'vmCpuPanel',
                                                    margin: 0,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            html: '<center><b>CPU</b></center>',
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;}'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            hidden: true,
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                                            text: ''
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'vmMemoryPanel',
                                                    margin: 0,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            html: '<center><b>Mem</b></center>',
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;}'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            hidden: true,
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                                            text: ''
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    itemId: 'vmNetworkPanel',
                                                    margin: '0 15 0 0',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            html: '<center><b>Net</b></center>',
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;}'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            height: 35,
                                                            hidden: true,
                                                            style: '{display:inline-block;padding-top:10px;height: 36px;text-align:center;}',
                                                            text: ''
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    header: false,
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'fieldset',
                            cls: 'vmhostinfo-fieldset',
                            frame: false,
                            margin: '15 30 15 15',
                            style: '',
                            collapsible: true,
                            title: 'VM Host 상세정보',
                            items: [
                                {
                                    xtype: 'form',
                                    id: 'viewVmHostForm',
                                    itemId: 'viewVmHostForm',
                                    margin: '5 0 0 0',
                                    padding: '0 10 0 0',
                                    bodyPadding: '0 10 0 10',
                                    header: false,
                                    title: 'My Form',
                                    fieldDefaults: {
                                        readOnly: true,
                                        labelStyle: 'font-weight: bold;',
                                        labelWidth: 70,
                                        labelSeparator: ' :'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldcontainer',
                                            flex: '1',
                                            height: 30,
                                            margin: 0,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'displayfield',
                                                    flex: 1,
                                                    fieldLabel: '이름',
                                                    name: 'name'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    flex: 1,
                                                    fieldLabel: '센터',
                                                    name: 'location'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            fieldDefaults: {
                                                readOnly: true,
                                                labelStyle: 'color:#666;font-weight: bold;',
                                                labelWidth: 100,
                                                labelSeparator: ' :'
                                            },
                                            collapsible: true,
                                            title: '하드웨어 정보',
                                            items: [
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: '1',
                                                    height: 28,
                                                    margin: 0,
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'IP 주소',
                                                            name: 'addr'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'Host Name',
                                                            name: 'hostname'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: '1',
                                                    height: 28,
                                                    margin: 0,
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'CPU',
                                                            name: 'cpuModel'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'CPU 개수',
                                                            name: 'cpus'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: '1',
                                                    height: 28,
                                                    margin: 0,
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'CPU 소켓',
                                                            name: 'cpuSocket'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: '소켓 당 Core/Core 당 Thread',
                                                            labelWidth: 190,
                                                            name: 'cpuCore'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: '1',
                                                    height: 28,
                                                    margin: 0,
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'Memory',
                                                            name: 'memSize'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldset',
                                                    padding: 0,
                                                    title: '',
                                                    items: [
                                                        {
                                                            xtype: 'gridpanel',
                                                            height: 120,
                                                            margin: 0,
                                                            overflowY: 'auto',
                                                            header: false,
                                                            title: 'My Grid Panel',
                                                            forceFit: true,
                                                            store: 'VmHostInterfaceStore',
                                                            columns: [
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'macaddr',
                                                                    text: 'Mac Address',
                                                                    flex: 2
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'name',
                                                                    text: 'Name',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'state',
                                                                    text: 'Status',
                                                                    flex: 1
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            fieldDefaults: {
                                                readOnly: true,
                                                labelStyle: 'color:#666;font-weight: bold;',
                                                labelWidth: 100,
                                                labelSeparator: ' :'
                                            },
                                            collapsible: true,
                                            title: 'VM 정보',
                                            items: [
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: '1',
                                                    height: 28,
                                                    margin: 0,
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'Hypervisor',
                                                            name: 'hypervisor'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'API',
                                                            name: 'vmApi'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldcontainer',
                                                    flex: '1',
                                                    height: 28,
                                                    margin: 0,
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            fieldLabel: 'Library',
                                                            name: 'useLib'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 3
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                vmHostConstants.me.popAddVmWindow();
                            },
                            margin: '0 5 0 5',
                            text: 'VM  생성'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                button.up("window").close();
                            },
                            margin: '0 0 0 10',
                            padding: '3 8 3 8',
                            text: '닫기'
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 2
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                vmHostConstants.me.deleteVmHost(button);
                            },
                            margin: '0 30 0 0',
                            padding: '3 10 3 10',
                            text: 'VM Host 해제'
                        }
                    ]
                }
            ],
            listeners: {
                close: {
                    fn: me.onVMHostInfoWindowClose,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onVMHostInfoWindowClose: function(panel, eOpts) {
        clearInterval(vmHostConstants.chartInterval);

    }

});