/*
 * File: app/store/ServerListStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('spider.store.ServerListStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ServerListStore',
            root: {
                expanded: true,
                text: 'Server List',
                children: [
                    {
                        text: 'NFV Host - 192.168.0.1',
                        expanded: true,
                        children: [
                            {
                                text: 'NFV Guest 11',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 12',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 13',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 14',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.2',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 21',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 22',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 23',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 24',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.3',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 31',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 32',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 33',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 34',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.4',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 41',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 42',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 43',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 44',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.5',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 51',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 52',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 53',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 54',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.6',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 61',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 62',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 63',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 64',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.7',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 71',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 72',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 73',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 74',
                                leaf: true
                            }
                        ]
                    },
                    {
                        text: 'NFV Host - 192.168.0.8',
                        expanded: false,
                        children: [
                            {
                                text: 'NFV Guest 81',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 82',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 83',
                                leaf: true
                            },
                            {
                                text: 'NFV Guest 84',
                                leaf: true
                            }
                        ]
                    }
                ]
            },
            fields: [
                {
                    name: 'text'
                }
            ]
        }, cfg)]);
    }
});